// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class City
{
    public int CityId { get; set; }

    public int StateId { get; set; }

    public string CityName { get; set; }

    public bool? IsActive { get; set; }

    public bool IsDelete { get; set; }

    public DateTime? CreateDate { get; set; }

    public string CityCode { get; set; }

    public virtual ICollection<FicciErpCustomerDetail> FicciErpCustomerDetails { get; set; } = new List<FicciErpCustomerDetail>();

    public virtual State State { get; set; }
}