// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class FicciErpProjectDetail
{
    public int ProjectId { get; set; }

    public string ProjectNo { get; set; }

    public string ProjectName { get; set; }

    public string ProjectDivision { get; set; }

    public string ProjectDepartment { get; set; }

    public string ProjectCost { get; set; }

    public DateTime? ProjectUpdatedOn { get; set; }

    public bool? ProjectActive { get; set; }

    public bool IsDelete { get; set; }

    public string ProjectGst { get; set; }

    public string ProjectPan { get; set; }
}