// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class VwCustomerApprovalList
{
    public int CustomerId { get; set; }

    public string StatusName { get; set; }

    public string CustomerName { get; set; }

    public string CustoemrAddress { get; set; }

    public string CustomerPhoneNo { get; set; }

    public string CustomerEmailId { get; set; }

    public string CustomerPinCode { get; set; }

    public string CustomerLastname { get; set; }

    public string CustoemrAddress2 { get; set; }

    public string CustomerContactPerson { get; set; }

    public string CustomerGstNo { get; set; }

    public string CustomerPanNo { get; set; }

    public bool IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public string Createdby { get; set; }

    public string LastUpdateBy { get; set; }

    public string CustomerUpdatedOn { get; set; }

    public string CustomerTlApprover { get; set; }

    public string CustomerClusterApprover { get; set; }

    public string CustomerSgApprover { get; set; }

    public string CityName { get; set; }

    public string CustomerTypeName { get; set; }

    public string ApproverEmail { get; set; }
}