// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FICCI_API.ModelsEF;

public partial class VwInvoiceApprovalList
{
    public int ImpiHeaderId { get; set; }

    public string ImpiHeaderPiNo { get; set; }

    public string ImpiHeaderInvoiceType { get; set; }

    public string ImpiHeaderProjectDivisionCode { get; set; }

    public string ImpiHeaderPanNo { get; set; }

    public string ImpiHeaderGstNo { get; set; }

    public string ImpiHeaderCustomerCode { get; set; }

    public string ImpiHeaderCustomerCity { get; set; }

    public string ImpiHeaderCustomerState { get; set; }

    public string ImpiHeaderCustomerPinCode { get; set; }

    public string ImpiHeaderCustomerGstNo { get; set; }

    public string ImpiHeaderCustomerEmailId { get; set; }

    public string ImpiHeaderCustomerPhoneNo { get; set; }

    public string ImpiHeaderCreatedBy { get; set; }

    public DateTime? ImpiHeaderSubmittedDate { get; set; }

    public decimal? ImpiHeaderTotalInvoiceAmount { get; set; }

    public string ImpiHeaderPaymentTerms { get; set; }

    public string ImpiHeaderRemarks { get; set; }

    public int? HeaderStatusId { get; set; }

    public string StatusName { get; set; }

    public string ApproverEmail { get; set; }
}